name: 'Docker Build'
on:
  push:
    branches: [ 'default' ]

jobs:
  docker:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v4'
      - name: 'Setup Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'
      - name: 'Login to GitHub Container Registry'
        uses: 'docker/login-action@v3'
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Build & Push Docker image'
        uses: 'docker/build-push-action@v6'
        with:
          context: '.'
          push: 'true'
          tags: |
            ghcr.io/sfenker/rust-server:latest
            ghcr.io/sfenker/rust-server:${{ github.sha }}
          cache-from: type=gha,scope=rust-server
          cache-to: type=gha,mode=max,scope=rust-server